version: 1
update_configs:
- package_manager: javascript
  directory: /
  update_schedule: live
  default_milestone: 1
  version_requirement_updates: increase_versions
  allowed_updates:
  - match:
      # update_type: all
      update_type: security
  - match:
      dependency_type: direct

- package_manager: docker
  directory: /
  update_schedule: daily
  default_milestone: 1
