name: CrowdIn Translations
on:
  check_suite:
    types:
    - completed
    branches:
    - crowdin
  pull_request:
    types:
    - labeled
    - unlabeled
    - synchronize
    - opened
    - edited
    - ready_for_review
    - reopened
    - unlocked
    branches:
    - crowdin

jobs:
  merge:
    name: Sync
    if: github.ref == 'ref/heads/crowdin'
    runs-on: ubuntu-latest
    steps:
    - uses: pascalgn/automerge-action@v0.11.0
      env:
        MERGE_LABELS: ''
        MERGE_METHOD: squash
        MERGE_FILTER_AUTHOR: wopian
        MERGE_FORKS: false
        MERGE_RETRY_SLEEP: 600000 # 10 minutes in milliseconds
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
